### PR TITLE
Adding new parameter

### PR DESCRIPTION
**Pull request by Psychosynthesis**
Hello.

Sometimes it is very convenient to be able to turn off the display of the timer on the page.

### CODE REVIEW

**Comment by walmik** [comment]
Hi @Psychosynthesis ! Thank you for your interest in improving the timer plugin. Please do note that PRs need to be created with adequate tests added for the features they introduce/update. Additionally could you please explain a real world scenario where starting timer in a hidden way would be useful? I just want to make sure we dont introduce something that could ve been entirely handled via `setInterval` or `setTimeout` alone.

**Comment by Psychosynthesis** [comment]
Hi!
The example is rather trivial: if the application specifies the default date in a human-readable format (such as "1h29m"), and already uses your library somewhere, then, if necessary, you can simply use your timer with the parameter "hidden" instead of setInterval \ setTimeout and, at least, get rid of the extra conversion in milliseconds.

**Comment by Psychosynthesis** [comment]
Well, in general, I could come up with a couple more scenarios, of course ...

... but I will say shortly. In my particular case, it seemed to me that using your library was simply more convenient than setInterval \ setTimeout, but I did not need the output to the block.

As a result, I had to add style to hide the block with the timer.

**Comment by walmik** [comment]
It sure makes sense. I think it’s a good thing to add. Please add few tests to your PR to cover your feature.

**Comment by Psychosynthesis** [comment]
Sorry, I believe that I do not fully understand how testing works in your project. Also, I see that you are using grunt for this.

I guess I can not finish the job due to lack of experience.

**Comment by walmik** [comment]
Dont worry, I understand. I ll add the tests later. For now please bump the package minor version as part of this PR. Basically make it `0.9.0` in this file on this line: 
https://github.com/walmik/timer.jquery/blob/master/package.json#L5

**Comment by walmik** [comment]
@Psychosynthesis i m merging this in. I ll update the package and add tests.

**Pull request merged**
